/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import com.toedter.calendar.JCalendar;
import com.toedter.calendar.JDateChooser;
import java.text.SimpleDateFormat;

/**
 *
 * @author SERYN
 */
public class reports extends javax.swing.JFrame {

    /**
     * Creates new form mainmenu
     */
    public reports() {
        initComponents();
        
        loadReports();
        showDate();
        showTime();
    }
    
    public void loadReports(){
   DefaultTableModel model = (DefaultTableModel) tblReports.getModel();
    model.setRowCount(0);

    try {
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory_db", "root", "");
        String reportType = reporttype.getSelectedItem().toString();
        String sql = "";

        if (reportType.equals("Low Stocks")) {
            sql = "SELECT * FROM products WHERE quantity <= 5 AND quantity > 0";
        } else if (reportType.equals("Out of Stocks")) { 
            sql = "SELECT * FROM products WHERE quantity = 0";
        } else if (reportType.equals("Available Stocks")) {
            sql = "SELECT * FROM products WHERE quantity > 5";
        } else {
            sql = "SELECT * FROM products";
        }

        PreparedStatement pst = con.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            int quantity = rs.getInt("quantity");
            double price = rs.getDouble("price");
            double itemValuation = price * quantity;
            
            String descriptionValue;
            if (quantity == 0) {
                descriptionValue = " Needs immediate reorder re-stocking!";
            } else {
                descriptionValue = String.format("Total Value: ₱%.2f", itemValuation);
            }

            model.addRow(new Object[] {
                rs.getInt("product_id"),
                rs.getString("product_name"),
                rs.getString("category"),
                quantity,
                "php" + String.format("%.2f", price), 
                descriptionValue,
                rs.getDate("date") 
            });
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error compilation tracking data: " + e);
    }
    }
     public void showDate(){
       java.util.Date d = new java.util.Date();
        
        SimpleDateFormat sdt = new SimpleDateFormat("MMMM dd, yyyy");
        
        date.setText(sdt.format(d));
    }
     public void showTime(){
        new javax.swing.Timer(1000, e ->{
            java.util.Date d = new java.util.Date();
            
            SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
            
            Time.setText(s.format(d));
            
        }).start();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        reporttype = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        date_to = new com.toedter.calendar.JDateChooser();
        date_from = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblReports = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        date = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REPORTS");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(0, 78, 181));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("INVENTORY MANAGEMENT SYSTEM");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Main Menu");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setText("Product Management");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3.setText("Inventory");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton4.setText("Stock Monitoring");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(51, 51, 51));
        jButton5.setText("Reports");
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton16.setBackground(new java.awt.Color(255, 255, 255));
        jButton16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton16.setText("Log out");
        jButton16.setBorder(null);
        jButton16.setBorderPainted(false);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addGap(55, 55, 55)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168)
                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Reports");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("View and export inventory reports.");

        jPanel3.setBackground(new java.awt.Color(255, 252, 245));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Report Type:");

        reporttype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Stock Summary", "Low Stocks", "Out of Stocks", "Available Stocks" }));
        reporttype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporttypeActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Date From:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Date To:");

        jButton13.setBackground(new java.awt.Color(255, 178, 74));
        jButton13.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("Export PDF");
        jButton13.setBorderPainted(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton17.setBackground(new java.awt.Color(0, 149, 74));
        jButton17.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton17.setForeground(new java.awt.Color(255, 255, 255));
        jButton17.setText("Generate Report");
        jButton17.setBorderPainted(false);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        date_to.setDateFormatString("yyyy-MM-d");

        date_from.setDateFormatString("yyyy-MM-d");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reporttype, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(date_from, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(date_to, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(202, Short.MAX_VALUE)
                .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(246, 246, 246))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(date_to, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(date_from, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(reporttype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 252, 245));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Report Result");

        tblReports.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Product Id", "Product Name", "Category", "Quantity", "Price", "Description", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblReports.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblReports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblReportsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblReports);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 915, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel13.setBackground(new java.awt.Color(255, 178, 74));
        jPanel13.setForeground(new java.awt.Color(255, 178, 74));

        date.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        date.setText("Date");

        Time.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        Time.setText("Time");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Time)
                    .addComponent(date))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(date)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Time)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel1))
                        .addGap(524, 524, 524)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23))
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 670));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         new productmanagement().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new mainmenu().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         new inventory().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
          new stock().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         new reports().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
       int response = JOptionPane.showConfirmDialog( null, "Are you sure you want to log out?", "Confirm Logout", JOptionPane.YES_NO_OPTION);
    //Checking if they clicked "YES"
    if (response == JOptionPane.YES_OPTION) {
    // Opens the new login frame
    new login().setVisible(true);
    this.dispose(); 
    }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void tblReportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblReportsMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_tblReportsMouseClicked

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    if (date_from.getDate() == null || date_to.getDate() == null) {
        JOptionPane.showMessageDialog(null, "Please select both 'From' and 'To' dates.");
        return;
    }

    DefaultTableModel model = (DefaultTableModel) tblReports.getModel();
    model.setRowCount(0);

    try {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String dateFrom = sdf.format(date_from.getDate());
        String dateTo = sdf.format(date_to.getDate());

        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory_db", "root", "");
     
        String reportType = reporttype.getSelectedItem().toString();
        String sql = "";

        if (reportType.equals("Low Stocks")) {
            sql = "SELECT * FROM products WHERE (quantity <= 5 AND quantity > 0) AND date BETWEEN ? AND ?";
        } else if (reportType.equals("Out of Stocks")) { 
            sql = "SELECT * FROM products WHERE quantity = 0 AND date BETWEEN ? AND ?";
        } else if (reportType.equals("Available Stocks")) {
            sql = "SELECT * FROM products WHERE quantity > 5 AND date BETWEEN ? AND ?";
        } else {
            sql = "SELECT * FROM products WHERE date BETWEEN ? AND ?";
        }

        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, dateFrom);
        pst.setString(2, dateTo);

        ResultSet rs = pst.executeQuery();

        StringBuilder reportBuilder = new StringBuilder();
        reportBuilder.append("=========================================================================================================\n");
        reportBuilder.append(String.format("                               INVENTORY REPORT (%s)\n", reportType.toUpperCase()));
        reportBuilder.append(String.format("                               Date Range: %s to %s\n", dateFrom, dateTo));
        reportBuilder.append("=========================================================================================================\n\n");
        
    
        reportBuilder.append(String.format("%-25s | %-15s | %-6s | %-12s | %-12s | %-25s\n", 
                "Product Name", "Category", "Qty", "Price", "Date", "Description"));
        reportBuilder.append("---------------------------------------------------------------------------------------------------------\n");

        boolean hasRecords = false;
        while(rs.next()) {
            hasRecords = true;
            int quantity = rs.getInt("quantity");
            double price = rs.getDouble("price");
            String productName = rs.getString("product_name");
            String category = rs.getString("category");
            Date rDate = rs.getDate("date");

            double itemValuation = price * quantity;
            String descriptionValue;
            if (quantity == 0) {
                descriptionValue = "Needs immediate reorder!";
            } else {
                descriptionValue = String.format("Valuation: ₱%.2f", itemValuation);
            }

            model.addRow(new Object[]{
                rs.getInt("product_id"),
                productName,
                category,
                quantity,
                "₱" + String.format("%.2f", price),
                descriptionValue,
                rDate
            });

            reportBuilder.append(String.format("%-25s | %-15s | %-6d | ₱%-11.2f | %-12s | %-25s\n", 
                    productName, 
                    category, 
                    quantity, 
                    price, 
                    (rDate != null ? rDate.toString() : "N/A"), 
                    descriptionValue));
        }
        
        reportBuilder.append("==================================================================================================\n");

        if (!hasRecords) {
            JOptionPane.showMessageDialog(null, "No data matches your specified date range filters.", "Report Summary", JOptionPane.INFORMATION_MESSAGE);
        } else { 
            javax.swing.JTextArea textArea = new javax.swing.JTextArea(reportBuilder.toString());
            textArea.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 12));
            textArea.setEditable(false);

            javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(textArea);
            scrollPane.setPreferredSize(new java.awt.Dimension(850, 450));

            JOptionPane.showMessageDialog(null, scrollPane, "Generated Text Report Summary", JOptionPane.PLAIN_MESSAGE);
        }
    } catch(Exception e) {
        JOptionPane.showMessageDialog(null, "Error tracking date reports: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_jButton17ActionPerformed

    private void reporttypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporttypeActionPerformed
        // TODO add your handling code here:
        loadReports();
    }//GEN-LAST:event_reporttypeActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed

    if (date_from.getDate() == null || date_to.getDate() == null) {
        JOptionPane.showMessageDialog(null, "Please select both 'From' and 'To' dates before exporting.");
        return;
    }

    javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
    fileChooser.setDialogTitle("Specify a File Location to Save Your PDF Report");
   
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    String dateFrom = sdf.format(date_from.getDate());
    String dateTo = sdf.format(date_to.getDate());
    
    fileChooser.setSelectedFile(new java.io.File("Inventory_Report_" + dateFrom + "_to_" + dateTo + ".pdf"));

    int userSelection = fileChooser.showSaveDialog(this);
    if (userSelection != javax.swing.JFileChooser.APPROVE_OPTION) {
        return; 
    }

    java.io.File fileToSave = fileChooser.getSelectedFile();
    String pdfPath = fileToSave.getAbsolutePath();
    
    if (!pdfPath.toLowerCase().endsWith(".pdf")) {
        pdfPath += ".pdf";
    }

    try {
        com.lowagie.text.Document document = new com.lowagie.text.Document(com.lowagie.text.PageSize.A4, 36, 36, 54, 36);
        com.lowagie.text.pdf.PdfWriter.getInstance(document, new java.io.FileOutputStream(pdfPath));
        
        document.open();

        com.lowagie.text.Font titleFont = new com.lowagie.text.Font(com.lowagie.text.Font.HELVETICA, 18, com.lowagie.text.Font.BOLD, java.awt.Color.WHITE);
        com.lowagie.text.Font metaFont = new com.lowagie.text.Font(com.lowagie.text.Font.HELVETICA, 10, com.lowagie.text.Font.NORMAL, java.awt.Color.DARK_GRAY);
        com.lowagie.text.Font headFont = new com.lowagie.text.Font(com.lowagie.text.Font.HELVETICA, 10, com.lowagie.text.Font.BOLD, java.awt.Color.WHITE);
        com.lowagie.text.Font cellFont = new com.lowagie.text.Font(com.lowagie.text.Font.HELVETICA, 9, com.lowagie.text.Font.NORMAL, java.awt.Color.BLACK);

        com.lowagie.text.pdf.PdfPTable headerBanner = new com.lowagie.text.pdf.PdfPTable(1);
        headerBanner.setWidthPercentage(100);
        com.lowagie.text.pdf.PdfPCell bannerCell = new com.lowagie.text.pdf.PdfPCell(new com.lowagie.text.Paragraph("INVENTORY SYSTEM SUMMARY REPORT", titleFont));
        bannerCell.setBackgroundColor(new java.awt.Color(0, 78, 181)); 
        bannerCell.setPadding(12);
        bannerCell.setHorizontalAlignment(com.lowagie.text.Element.ALIGN_CENTER);
        bannerCell.setBorder(com.lowagie.text.Rectangle.NO_BORDER);
        headerBanner.addCell(bannerCell);
        document.add(headerBanner);

        String reportType = reporttype.getSelectedItem().toString();
        document.add(new com.lowagie.text.Paragraph("\nReport Parameter Filter Type: " + reportType, metaFont));
        document.add(new com.lowagie.text.Paragraph("Date Filtering Bounds: " + dateFrom + " through " + dateTo, metaFont));
        document.add(new com.lowagie.text.Paragraph("Generated System Date: " + date.getText() + " at " + Time.getText() + "\n\n", metaFont));

        com.lowagie.text.pdf.PdfPTable pdfTable = new com.lowagie.text.pdf.PdfPTable(7);
        pdfTable.setWidthPercentage(100);
        pdfTable.setWidths(new float[]{1.0f, 2.5f, 2.0f, 1.2f, 1.8f, 3.0f, 1.8f}); 

        String[] headers = {"Prod ID", "Product Name", "Category", "Quantity", "Price", "Description Valuation", "Log Date"};
        for (String headerText : headers) {
            com.lowagie.text.pdf.PdfPCell hCell = new com.lowagie.text.pdf.PdfPCell(new com.lowagie.text.Paragraph(headerText, headFont));
            hCell.setBackgroundColor(new java.awt.Color(15, 23, 42)); 
            hCell.setPadding(8);
            hCell.setHorizontalAlignment(com.lowagie.text.Element.ALIGN_CENTER);
            pdfTable.addCell(hCell);
        }

        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory_db", "root", "");
        String sql = "";

        if (reportType.equals("Low Stocks")) {
            sql = "SELECT * FROM products WHERE (quantity <= 5 AND quantity > 0) AND date BETWEEN ? AND ?";
        } else if (reportType.equals("Out of Stocks")) { 
            sql = "SELECT * FROM products WHERE quantity = 0 AND date BETWEEN ? AND ?";
        } else if (reportType.equals("Available Stocks")) {
            sql = "SELECT * FROM products WHERE quantity > 5 AND date BETWEEN ? AND ?";
        } else {
            sql = "SELECT * FROM products WHERE date BETWEEN ? AND ?";
        }

        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, dateFrom);
        pst.setString(2, dateTo);
        ResultSet rs = pst.executeQuery();

        boolean rowAlternateColor = false;
        double overallGrandTotalAssetPool = 0;
        int documentedItemCount = 0;

        while (rs.next()) {
            documentedItemCount++;
            int id = rs.getInt("product_id");
            String name = rs.getString("product_name");
            String cat = rs.getString("category");
            int qty = rs.getInt("quantity");
            double price = rs.getDouble("price");
            java.sql.Date dLog = rs.getDate("date");

            double valuation = price * qty;
            overallGrandTotalAssetPool += valuation;

            String descStr = (qty == 0) ? "Needs Immediate Restock!" : String.format("Total: PHP %.2f", valuation);
            String dateStr = (dLog != null) ? dLog.toString() : "N/A";

            String[][] rowCells = {
                {String.valueOf(id), "C"}, {name, "L"}, {cat, "L"}, 
                {String.valueOf(qty), "C"}, {String.format("PHP %.2f", price), "R"}, 
                {descStr, "L"}, {dateStr, "C"}
            };

            for (String[] cellData : rowCells) {
                com.lowagie.text.pdf.PdfPCell dataCell = new com.lowagie.text.pdf.PdfPCell(new com.lowagie.text.Paragraph(cellData[0], cellFont));
                dataCell.setPadding(6);
                
                if (cellData[1].equals("C")) dataCell.setHorizontalAlignment(com.lowagie.text.Element.ALIGN_CENTER);
                else if (cellData[1].equals("R")) dataCell.setHorizontalAlignment(com.lowagie.text.Element.ALIGN_RIGHT);
                else dataCell.setHorizontalAlignment(com.lowagie.text.Element.ALIGN_LEFT);
                if (rowAlternateColor) {
                    dataCell.setBackgroundColor(new java.awt.Color(245, 247, 250));
                } else {
                    dataCell.setBackgroundColor(java.awt.Color.WHITE);
                }
                pdfTable.addCell(dataCell);
            }
            rowAlternateColor = !rowAlternateColor; 
        }

        document.add(pdfTable);

        document.add(new com.lowagie.text.Paragraph("\n------------------------------------------------------------------------------------------------------------------------"));
        com.lowagie.text.Font summaryFont = new com.lowagie.text.Font(com.lowagie.text.Font.HELVETICA, 11, com.lowagie.text.Font.BOLD, new java.awt.Color(30, 41, 59));
        document.add(new com.lowagie.text.Paragraph(String.format("Total Unique Items Documented: %d rows", documentedItemCount), summaryFont));
        document.add(new com.lowagie.text.Paragraph(String.format("Total Cumulative Inventory Valuation: PHP %.2f", overallGrandTotalAssetPool), summaryFont));
        document.add(new com.lowagie.text.Paragraph("------------------------------------------------------------------------------------------------------------------------"));

        document.close();
        con.close();

        if (java.awt.Desktop.isDesktopSupported()) {
            java.awt.Desktop.getDesktop().open(new java.io.File(pdfPath));
        } else {
            JOptionPane.showMessageDialog(null, "PDF successfully saved to:\n" + pdfPath, "Export Successful", JOptionPane.INFORMATION_MESSAGE);
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error writing PDF file: " + e.getMessage(), "PDF Export Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Time;
    private javax.swing.JLabel date;
    private com.toedter.calendar.JDateChooser date_from;
    private com.toedter.calendar.JDateChooser date_to;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox reporttype;
    private javax.swing.JTable tblReports;
    // End of variables declaration//GEN-END:variables
}
